FROM python:3.9-slim

WORKDIR /usr/src/app

COPY ./producer/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY ./producer .

COPY ./domain ./domain

RUN pip install -e ./domain

CMD ["faust", "-A", "app", "worker", "-l", "info"]